services:
  mongo:
    image: mongo:8.2.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: xinbaojian
      MONGO_INITDB_ROOT_PASSWORD: JD0PjLYMZd1QPrQHyHWF
      MONGO_INITDB_DATABASE: xiuyuan-db
    ports:
      - 27017:27017
    volumes:
      - ./datadir:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    restart: always
    networks:
      - xiuyuan-network
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
        reservations:
          cpus: '1.00'
          memory: 256M
  redis:
    image: redis:latest
    command: redis-server --requirepass U2FsdGVkX182WAz5KErsYO
    ports:
      - 6379:6379
    # volumes:
    #   - /etc/localtime:/etc/localtime
    restart: always
    networks:
      - xiuyuan-network
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "9000:9000"   # S3 API 对外端口
      - "9001:9001"   # 控制台对外端口
    environment:
      # 数据卷（多个路径用逗号分隔）
      - RUSTFS_VOLUMES=/data/rustfs0
      # API 和控制台监听地址
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      # CORS 设置，控制台与 S3 API 都放开来源
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      # 访问密钥（生产环境请修改为强密码）
      - RUSTFS_ACCESS_KEY=xinbaojian
      - RUSTFS_SECRET_KEY=Xbj2025!@#
      # 日志级别
      - RUSTFS_OBS_LOGGER_LEVEL=info

    volumes:
      # 存储数据卷（请根据实际情况修改路径）
      - ./rustfs/data/pro:/data
      # 日志目录
      - ./rustfs/logs:/app/logs

    networks:
      - xiuyuan-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  xiuyuan-network:
    driver: bridge