server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  application:
    name: xiuyuan-admin
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB